package com.frontparissportifs.network

data class TeamResponse(val teams: List<TeamObjectResponse>)


data class TeamObjectResponse(
    val idAPIfootball: String,
    val idLeague: String?,
    val idLeague2: String?,
    val idLeague3: String?,
    val idLeague4: String?,
    val idLeague5: String?,
    val idLeague6: String?,
    val idLeague7: String?,
    val idSoccerXML: Any,
    val idTeam: String,
    val intFormedYear: String,
    val intLoved: Any,
    val intStadiumCapacity: String,
    val strAlternate: String,
    val strCountry: String,
    val strDescriptionCN: String?,
    val strDescriptionDE: String?,
    val strDescriptionEN: String,
    val strDescriptionES: String?,
    val strDescriptionFR: String?,
    val strDescriptionHU: String?,
    val strDescriptionIL: String?,
    val strDescriptionIT: String?,
    val strDescriptionJP: String?,
    val strDescriptionNL: String?,
    val strDescriptionNO: String?,
    val strDescriptionPL: String?,
    val strDescriptionPT: String?,
    val strDescriptionRU: String?,
    val strDescriptionSE: String?,
    val strDivision: Any,
    val strFacebook: String,
    val strGender: String,
    val strInstagram: String,
    val strKeywords: String,
    val strKitColour1: String,
    val strKitColour2: String,
    val strKitColour3: String,
    val strLeague: String?,
    val strLeague2: String?,
    val strLeague3: String?,
    val strLeague4: String?,
    val strLeague5: String?,
    val strLeague6: String?,
    val strLeague7: String?,
    val strLocked: String,
    val strManager: String,
    val strRSS: String,
    val strSport: String,
    val strStadium: String,
    val strStadiumDescription: String,
    val strStadiumLocation: String,
    val strStadiumThumb: Any,
    val strTeam: String,
    val strTeamBadge: String,
    val strTeamBanner: String?,
    val strTeamFanart1: Any,
    val strTeamFanart2: Any,
    val strTeamFanart3: Any,
    val strTeamFanart4: Any,
    val strTeamJersey: Any,
    val strTeamLogo: Any,
    val strTeamShort: Any,
    val strTwitter: String,
    val strWebsite: String,
    val strYoutube: String

)